spring:
  boot:
    admin:
      client:
        url: http://localhost:8090
  management:
    endpoints:
      web:
        exposure:
          include: '*'   
  application:
    name:  DATACOLLECTION-API
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/insurence-application
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
server:
  port: 8081